## Group 3  Muxing Wang (s2201749); Nutsa Tokhadze (s1778736); Karla Itzel Vega Ortega (s2126801) 
## Address of github repo: https://github.com/leafstar/Statistical-Programming


# A BFGS optimizer #
# Overview #

#   The aim of the project is to implement optimization with BFGS quasi-Newton minimization method. Maximum likelihood 
# optimization, and many other statistical learning approaches, rely on numerical optimization. Optimization is finding a 
# maximum or minimum of a function. Broyden–Fletcher–Goldfarb–Shanno (BFGS) algorithm is one of the optimiazation methods 
# that approximate the second derivative (Hessian) where the second derivative cannot be calculated. It updates the inverse
# approximate Hessian, thereby avoiding the need for a matrix solve. The BFGS algorithm is perhaps one of the most widely
# used second-order algorithms for numerical optimization.

# Outline #

#  The Task is to write an R function, bfgs, implementing the BFGS quasi-Newton minimization method. Bfgs function should
# return: (1) f -the scalar value of the objective function at the minimum, (2) theta -the vector of values of the parameters 
# at the minimum, (3) iter- the number of iterations taken to reach the minimum, (4) g - the gradient vector at the minimum and
# (5) H - the approximate Hessian matrix.
#  Additionally, function should issue errors or warnings in at least the following cases. (1) If the objective or derivatives 
# are not finite at the initial theta; (2) If the step fails to reduce the objective but convergence has not occurred (3) If 
# maxit is reached without convergence and (4) If the supplied f does not supply a gradient attribute when requested- in this 
# case the gradient by finite differencing is computed. 
#  There are other considerations as well: (1) if a step leads to a non-finite objective value the step length must be reduced.
# Step length must reduce the objective function and satisfie the second Wolfe condition (use c2 = 0.9). (2) To judge whether 
# the gradient vector is close enough to zero, the magnitude of the objective must be beconsidered (3) The final approximate 
# Hessian matrix can be generated by finite differencing the gradient vector. Such an approximate Hessian will be asymmetric 
# which must be fixed (4)If p is the number of parameters, then the update of the approximate inverse Hessian should have cost
# O(p^2) not O(p^3). 
# for this purpose following functions were created....
# (1) 
# (2)
# (3)

# 1 #

get_step_size <- function(f,theta,d){
  upper_bound = 10
  lower_bound = 0
  max.iter = 20 # since we are doing a exponential decay, this bound is big enough for us to find a small step size.
  iter = 0
  eps = 1e-7
  c1 = 0.1 # for cond1
  c2 = 0.9 # we can discuss with simon about this since c2 is auto satisfied.
  alpha = 1
  theta.prime = theta + alpha*d
  g = get_grad(f,theta,eps)
  gamma = c1*sum(g*d) # for cond1 just as the video said
  cat("gamma",gamma,"\n")
  while(iter <= max.iter){
    iter = iter + 1
    g.prime = get_grad(f, theta.prime, eps)
    if(f(theta.prime) < f(theta) + alpha* gamma && g.prime %*% d /(g %*% d) <= c2){
      break
    }
    
    if(f(theta.prime) >= f(theta) + alpha* gamma){
      alpha = alpha/2
    }
    
    if(g.prime %*% d /(g %*% d) > c2){
      alpha = 1.1 * alpha
    }
    theta.prime = theta + alpha*d
  }
  
  print(g.prime %*% d /(g %*% d) <= c2)
  
  if(f(theta.prime) > f(theta)) warning("we cannot find a valid step size")

  alpha
}


# 2 #

get_grad <- function(f,theta,eps){
  if(is.null(attributes(f(theta, TRUE))$gradient)){
    ## finite differencing
    grad = theta
    for (i in 1:length(theta)) { ## loop over parameters
      theta1 <- theta; theta1[i] <- theta1[i] + eps ## increase th0[i] by eps nll1 <- nll(th1,t=t80,y=y) ## compute resulting nll
      grad[i] <- (f(theta1) - f(theta))/eps ## approximate -dl/dth[i]
    }
    as.vector(grad)
  }else{
    g.k = attributes(f(theta, TRUE))$gradient
  }
}

# 3 #

# This bfgs function returns a (named) list containing: (1) f -the scalar value of the objective function at the minimum, 
# (2) theta -the vector of values of the parameters at the minimum, (3) iter- the number of iterations taken to reach the minimum, 
# (4) g - the gradient vector at the minimum and (5) H - the approximate Hessian matrix.Theta is a vector of initial values for the 
# optimization parameters.
# f is the objective function to minimize Its first argument is the vector of optimization 
# parameters. Its second argument is a logical indicating whether or not gradients of the 
# objective w.r.t. the parameters should be computed
# Remaining arguments will be passed from bfgs using ...
# The scalar value returned by f will have a gradient attribute if the second argument to
# f is TRUE.
# tol the convergence tolerance
# fscale a rough estimate of the magnitude of f at the optimum - used in convergence testing
# maxit the maximum number of BFGS iterations to try before giving up

bfgs <- function(theta,f,...,tol=1e-5,fscale=1,maxit=100){
  theta.k = theta
  B.k <- I <- diag(length(theta))
  f0 = f(theta.k)
  eps = 1e-7 ## finite difference interval
  g.k = get_grad(f, theta.k, eps) ## initialize a random gradient
  
  if(any(is.infinite(g.k))) stop("gradient is not finite")
  if(is.infinite(f0)) stop("objective value is not finite")
  
  iter = 0
  
  while(max(abs(g.k)) >= (abs(f0)+fscale)*tol && iter <= maxit){
    f0 = f(theta.k)
    
    
    g.k = get_grad(f, theta.k, eps)
    
    
    d = -B.k %*% g.k
    
    
    alpha = get_step_size(f, theta.k, d)
    print(alpha)
    theta.kprime = as.vector(theta.k + alpha * d)
    
    g.kprime = get_grad(f, theta.kprime, eps)
    
    
    ## no need just checking the c2 condition
    print(g.kprime %*% d /(g.k %*% d))
    
    
    s.k = theta.kprime - theta.k
    y.k = g.kprime - g.k
    
    rho.k.i = sum(s.k*y.k)
    rho.k = 1/rho.k.i
    
    
    ## faster implementation
    B.kprime = B.k + ((rho.k.i+ as.vector(t(y.k)%*%B.k%*%y.k))*s.k %*% t(s.k))/(rho.k.i**2) - (B.k%*%y.k%*%t(s.k)+s.k%*%(t(y.k)%*%B.k))/rho.k.i
    
    theta.k = theta.kprime
    B.k = B.kprime
    iter = iter + 1
    
  }
  
  if(iter > maxit) warning("max iteration has been reached")
  
  
  ## fast way to compute H as B^-1
  H = chol2inv(chol(B.k))
  
  if (!isSymmetric(H)){
    H <- 0.5 * (t(H) + H)
  }
  
  cat("optim val", f(theta.k), "\n")
  list(f=f, theta=theta.k, iter=iter, g=g.k, H=H)
}

#  end  of   implementation 
########################
########################

### just for test, will delete everything below this

bfgs(c(-1,2),rb)

f = boha1
init = c(-1,2)
res1 = bfgs(init,f)
res2 = optim(init,f,method = "BFGS", hessian = TRUE)
res3 = nlm(f,init,hessian = TRUE)

cat("theta", res1$theta,"\n", res2$par, "\n", res3$estimate, "\n")

cat("hessian",res1$H,"\n", res2$hessian, "\n", res3$hessian,"\n")

cat("num_iteration",res1$iter, ",", res3$iterations)

cat(res2$value,",", res3$minimum,"\n")
#setwd(dirname(rstudioapi::getSourceEditorContext()$path))
#source("./p4_functions.R")
